services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: db
    
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    ports: 
      - "${DB_PORT}:5432"
    
    restart: always

volumes:
  postgres_data: